### ISSUE TITLE
Hekate 404

### ISSUE THREAD

**Issue by techflashYT** [lordfriky/web-cfw-loader#75] opened 2023-05-12 14:05 UTC
When loading hekate v6.0.4 from the menu.  It gives the following logs:
```
Requesting access to device...
There was a problem retreiving the payload. Error: Error: 404
```
I would test it more (like give JS Console output & any errors in network tab), but I'm currently on a school chromebook, and I can't access the devtools.  I will update this with more info once I get home.

UPDATE: Actually, I just tried using my previously downloaded 6.0.3 (update.bin exists so it should just autoload 6.0.4 anyways), and it just hangs with:
```
Requesting access to device...
Using uploaded payload "hekate_ctcaer_6.0.3.bin"
```
This is a bigger problem then I thought.  Again, I will test more when I get home and have access to a real Linux PC with both Firefox and Chromium.

**Comment by Wiilf** [comment] 2023-05-13 06:54
Test your millage even further - https://www.switch-torrents.com/cfw/loader/

I have a lot to update on this as I'm across 3 projects in 3 separate languages, bit busy but updates are coming. We havent had issues since launch. Of course, most people assume Windows as the default (not the case according to specs / engine restrictions).

I thought about implementing a Chrome addon, that inherits this request on site, and initiates the app to relay the data over to the that via custom prefix or token. But thats getting a little head of ourselves, for now I appear to have a alien copy of this JS that fulfills features that were missing originally. I just want to see the device list populated from a real 'original V1' Tegra. That's all I'm after.

Also showing users who sent successful payloads (we are a semi-social platform) will be coming up. That will entice others to jump in and get their OG V1 in RCM. Just completely in the dark as to whether this thing actually works or not (has anyone ever reported it to work?). Naturally priority drops in that regard. I just like to play around with UI and functionality.

**Comment by ctomichael** [comment] 2023-05-15 10:38
The issue is because `payloads.json` has the path for hekate 6.0.4 as `payloads/hekate-v6.0.3.bin`, when it should be 6.0.4.  


PR here: https://github.com/lordfriky/web-cfw-loader/pull/76

**Comment by lordfriky** [comment] 2023-05-16 21:52
This should be fixed now, thanks @ctomichael!

**Closed as completed by lordfriky** 2023-05-16 21:52 UTC
